# Generated by Django 5.0.2 on 2024-03-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.CharField(max_length=2000),
        ),
    ]
